%% ==============================================================
%% ACL - Control de acceso MQTT para Ecomóviles
%% Tópicos: vehiculos/{vehiculoId}/telemetria/admin
%%          vehiculos/{vehiculoId}/telemetria/publico
%% ==============================================================

%% 1. Servicio interno de distribución: Permitir publicar en ambos y denegar suscripciones
%% Esta regla se activa porque este usuario se autenticó vía base de datos local en el paso 1
{allow, {username, "servicio-distribucion"}, publish, ["vehiculos/+/telemetria/admin", "vehiculos/+/telemetria/publico"]}.
{deny,  {username, "servicio-distribucion"}, subscribe, ["$all"]}.

%% 2. Invitados (Tokens públicos): Bloquear del canal de administración
%% Usamos una expresión regular que coincidirá con el "service-account-ms-guest-client" extraído del JWT
{deny, {username, {re, "^service-account-.*"}}, subscribe, ["vehiculos/+/telemetria/admin"]}.

%% 3. Administradores e Invitados: Permitir suscripciones a los canales correspondientes
%% Los invitados ya fueron bloqueados del canal /admin en la regla 2, por lo que aquí solo obtendrán acceso a /publico.
%% Los administradores (ej. "devora") omiten la regla 2 por su nombre, llegan aquí y obtienen acceso a ambos.
{allow, all, subscribe, ["vehiculos/+/telemetria/publico", "vehiculos/+/telemetria/admin"]}.

%% 4. Regla de cierre: denegar todo lo no permitido explícitamente
{deny, all}.