/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.servicioTransporte.flota.eventos.vehiculo.configuracion;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Evento de sincronización de autorización de hardware GPS para la flota */
@org.apache.avro.specific.AvroGenerated
public class DispositivoGpsAutorizado extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3666985290812776304L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DispositivoGpsAutorizado\",\"namespace\":\"com.servicioTransporte.flota.eventos.vehiculo.configuracion\",\"doc\":\"Evento de sincronización de autorización de hardware GPS para la flota\",\"fields\":[{\"name\":\"gpsId\",\"type\":\"string\",\"doc\":\"Identificador único de hardware del GPS (IMEI o ID numérico)\"},{\"name\":\"matricula\",\"type\":[\"null\",\"string\"],\"doc\":\"Matrícula del vehículo asociado\",\"default\":null},{\"name\":\"activo\",\"type\":\"boolean\",\"doc\":\"true si está habilitado para emitir telemetría, false si fue revocado o desasignado\"},{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},\"doc\":\"Momento de emisión del evento en milisegundos UTC\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<DispositivoGpsAutorizado> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DispositivoGpsAutorizado> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DispositivoGpsAutorizado> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DispositivoGpsAutorizado> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DispositivoGpsAutorizado> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DispositivoGpsAutorizado to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DispositivoGpsAutorizado from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DispositivoGpsAutorizado instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DispositivoGpsAutorizado fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Identificador único de hardware del GPS (IMEI o ID numérico) */
  private java.lang.CharSequence gpsId;
  /** Matrícula del vehículo asociado */
  private java.lang.CharSequence matricula;
  /** true si está habilitado para emitir telemetría, false si fue revocado o desasignado */
  private boolean activo;
  /** Momento de emisión del evento en milisegundos UTC */
  private java.time.Instant timestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DispositivoGpsAutorizado() {}

  /**
   * All-args constructor.
   * @param gpsId Identificador único de hardware del GPS (IMEI o ID numérico)
   * @param matricula Matrícula del vehículo asociado
   * @param activo true si está habilitado para emitir telemetría, false si fue revocado o desasignado
   * @param timestamp Momento de emisión del evento en milisegundos UTC
   */
  public DispositivoGpsAutorizado(java.lang.CharSequence gpsId, java.lang.CharSequence matricula, java.lang.Boolean activo, java.time.Instant timestamp) {
    this.gpsId = gpsId;
    this.matricula = matricula;
    this.activo = activo;
    this.timestamp = timestamp.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return gpsId;
    case 1: return matricula;
    case 2: return activo;
    case 3: return timestamp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: gpsId = (java.lang.CharSequence)value$; break;
    case 1: matricula = (java.lang.CharSequence)value$; break;
    case 2: activo = (java.lang.Boolean)value$; break;
    case 3: timestamp = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'gpsId' field.
   * @return Identificador único de hardware del GPS (IMEI o ID numérico)
   */
  public java.lang.CharSequence getGpsId() {
    return gpsId;
  }


  /**
   * Sets the value of the 'gpsId' field.
   * Identificador único de hardware del GPS (IMEI o ID numérico)
   * @param value the value to set.
   */
  public void setGpsId(java.lang.CharSequence value) {
    this.gpsId = value;
  }

  /**
   * Gets the value of the 'matricula' field.
   * @return Matrícula del vehículo asociado
   */
  public java.lang.CharSequence getMatricula() {
    return matricula;
  }


  /**
   * Sets the value of the 'matricula' field.
   * Matrícula del vehículo asociado
   * @param value the value to set.
   */
  public void setMatricula(java.lang.CharSequence value) {
    this.matricula = value;
  }

  /**
   * Gets the value of the 'activo' field.
   * @return true si está habilitado para emitir telemetría, false si fue revocado o desasignado
   */
  public boolean getActivo() {
    return activo;
  }


  /**
   * Sets the value of the 'activo' field.
   * true si está habilitado para emitir telemetría, false si fue revocado o desasignado
   * @param value the value to set.
   */
  public void setActivo(boolean value) {
    this.activo = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return Momento de emisión del evento en milisegundos UTC
   */
  public java.time.Instant getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * Momento de emisión del evento en milisegundos UTC
   * @param value the value to set.
   */
  public void setTimestamp(java.time.Instant value) {
    this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new DispositivoGpsAutorizado RecordBuilder.
   * @return A new DispositivoGpsAutorizado RecordBuilder
   */
  public static com.servicioTransporte.flota.eventos.vehiculo.configuracion.DispositivoGpsAutorizado.Builder newBuilder() {
    return new com.servicioTransporte.flota.eventos.vehiculo.configuracion.DispositivoGpsAutorizado.Builder();
  }

  /**
   * Creates a new DispositivoGpsAutorizado RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DispositivoGpsAutorizado RecordBuilder
   */
  public static com.servicioTransporte.flota.eventos.vehiculo.configuracion.DispositivoGpsAutorizado.Builder newBuilder(com.servicioTransporte.flota.eventos.vehiculo.configuracion.DispositivoGpsAutorizado.Builder other) {
    if (other == null) {
      return new com.servicioTransporte.flota.eventos.vehiculo.configuracion.DispositivoGpsAutorizado.Builder();
    } else {
      return new com.servicioTransporte.flota.eventos.vehiculo.configuracion.DispositivoGpsAutorizado.Builder(other);
    }
  }

  /**
   * Creates a new DispositivoGpsAutorizado RecordBuilder by copying an existing DispositivoGpsAutorizado instance.
   * @param other The existing instance to copy.
   * @return A new DispositivoGpsAutorizado RecordBuilder
   */
  public static com.servicioTransporte.flota.eventos.vehiculo.configuracion.DispositivoGpsAutorizado.Builder newBuilder(com.servicioTransporte.flota.eventos.vehiculo.configuracion.DispositivoGpsAutorizado other) {
    if (other == null) {
      return new com.servicioTransporte.flota.eventos.vehiculo.configuracion.DispositivoGpsAutorizado.Builder();
    } else {
      return new com.servicioTransporte.flota.eventos.vehiculo.configuracion.DispositivoGpsAutorizado.Builder(other);
    }
  }

  /**
   * RecordBuilder for DispositivoGpsAutorizado instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DispositivoGpsAutorizado>
    implements org.apache.avro.data.RecordBuilder<DispositivoGpsAutorizado> {

    /** Identificador único de hardware del GPS (IMEI o ID numérico) */
    private java.lang.CharSequence gpsId;
    /** Matrícula del vehículo asociado */
    private java.lang.CharSequence matricula;
    /** true si está habilitado para emitir telemetría, false si fue revocado o desasignado */
    private boolean activo;
    /** Momento de emisión del evento en milisegundos UTC */
    private java.time.Instant timestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.servicioTransporte.flota.eventos.vehiculo.configuracion.DispositivoGpsAutorizado.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.gpsId)) {
        this.gpsId = data().deepCopy(fields()[0].schema(), other.gpsId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.matricula)) {
        this.matricula = data().deepCopy(fields()[1].schema(), other.matricula);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.activo)) {
        this.activo = data().deepCopy(fields()[2].schema(), other.activo);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[3].schema(), other.timestamp);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing DispositivoGpsAutorizado instance
     * @param other The existing instance to copy.
     */
    private Builder(com.servicioTransporte.flota.eventos.vehiculo.configuracion.DispositivoGpsAutorizado other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.gpsId)) {
        this.gpsId = data().deepCopy(fields()[0].schema(), other.gpsId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.matricula)) {
        this.matricula = data().deepCopy(fields()[1].schema(), other.matricula);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.activo)) {
        this.activo = data().deepCopy(fields()[2].schema(), other.activo);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[3].schema(), other.timestamp);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'gpsId' field.
      * Identificador único de hardware del GPS (IMEI o ID numérico)
      * @return The value.
      */
    public java.lang.CharSequence getGpsId() {
      return gpsId;
    }


    /**
      * Sets the value of the 'gpsId' field.
      * Identificador único de hardware del GPS (IMEI o ID numérico)
      * @param value The value of 'gpsId'.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.vehiculo.configuracion.DispositivoGpsAutorizado.Builder setGpsId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.gpsId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'gpsId' field has been set.
      * Identificador único de hardware del GPS (IMEI o ID numérico)
      * @return True if the 'gpsId' field has been set, false otherwise.
      */
    public boolean hasGpsId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'gpsId' field.
      * Identificador único de hardware del GPS (IMEI o ID numérico)
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.vehiculo.configuracion.DispositivoGpsAutorizado.Builder clearGpsId() {
      gpsId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'matricula' field.
      * Matrícula del vehículo asociado
      * @return The value.
      */
    public java.lang.CharSequence getMatricula() {
      return matricula;
    }


    /**
      * Sets the value of the 'matricula' field.
      * Matrícula del vehículo asociado
      * @param value The value of 'matricula'.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.vehiculo.configuracion.DispositivoGpsAutorizado.Builder setMatricula(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.matricula = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'matricula' field has been set.
      * Matrícula del vehículo asociado
      * @return True if the 'matricula' field has been set, false otherwise.
      */
    public boolean hasMatricula() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'matricula' field.
      * Matrícula del vehículo asociado
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.vehiculo.configuracion.DispositivoGpsAutorizado.Builder clearMatricula() {
      matricula = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'activo' field.
      * true si está habilitado para emitir telemetría, false si fue revocado o desasignado
      * @return The value.
      */
    public boolean getActivo() {
      return activo;
    }


    /**
      * Sets the value of the 'activo' field.
      * true si está habilitado para emitir telemetría, false si fue revocado o desasignado
      * @param value The value of 'activo'.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.vehiculo.configuracion.DispositivoGpsAutorizado.Builder setActivo(boolean value) {
      validate(fields()[2], value);
      this.activo = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'activo' field has been set.
      * true si está habilitado para emitir telemetría, false si fue revocado o desasignado
      * @return True if the 'activo' field has been set, false otherwise.
      */
    public boolean hasActivo() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'activo' field.
      * true si está habilitado para emitir telemetría, false si fue revocado o desasignado
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.vehiculo.configuracion.DispositivoGpsAutorizado.Builder clearActivo() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * Momento de emisión del evento en milisegundos UTC
      * @return The value.
      */
    public java.time.Instant getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * Momento de emisión del evento en milisegundos UTC
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.vehiculo.configuracion.DispositivoGpsAutorizado.Builder setTimestamp(java.time.Instant value) {
      validate(fields()[3], value);
      this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * Momento de emisión del evento en milisegundos UTC
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * Momento de emisión del evento en milisegundos UTC
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.vehiculo.configuracion.DispositivoGpsAutorizado.Builder clearTimestamp() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DispositivoGpsAutorizado build() {
      try {
        DispositivoGpsAutorizado record = new DispositivoGpsAutorizado();
        record.gpsId = fieldSetFlags()[0] ? this.gpsId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.matricula = fieldSetFlags()[1] ? this.matricula : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.activo = fieldSetFlags()[2] ? this.activo : (java.lang.Boolean) defaultValue(fields()[2]);
        record.timestamp = fieldSetFlags()[3] ? this.timestamp : (java.time.Instant) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DispositivoGpsAutorizado>
    WRITER$ = (org.apache.avro.io.DatumWriter<DispositivoGpsAutorizado>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DispositivoGpsAutorizado>
    READER$ = (org.apache.avro.io.DatumReader<DispositivoGpsAutorizado>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










