server:
  port: 8080

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
  security:
    oauth2:
        resourceserver:
          jwt:
            issuer-uri: ${ISSUER}
            jwk-set-uri: ${JWK_URL}
  main:
    web-application-type: REACTIVE

microservicios:
  gestionUri: ${GESTION_URI}
  discoveriUri: ${DISCOVERI_URI}
  controlDeIdentidad: ${CONTROL_DE_IDENTIDAD_URI}
  distribucionTelemetriaUri: ${SEGUIMIENTO_DISTRIBUCION_TELEMETRIA_URI}
  admin-secret: ${ADMIN_SECRET}
  user-secret: ${USER_SECRET}
