/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.servicioTransporte.flota.eventos.conductor.eliminar;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ConductorEliminado extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1518217324082064490L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ConductorEliminado\",\"namespace\":\"com.servicioTransporte.flota.eventos.conductor.eliminar\",\"fields\":[{\"name\":\"keycloakId\",\"type\":\"string\"},{\"name\":\"nombre\",\"type\":\"string\"},{\"name\":\"apellido\",\"type\":\"string\"},{\"name\":\"dni\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ConductorEliminado> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ConductorEliminado> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ConductorEliminado> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ConductorEliminado> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ConductorEliminado> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ConductorEliminado to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ConductorEliminado from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ConductorEliminado instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ConductorEliminado fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence keycloakId;
  private java.lang.CharSequence nombre;
  private java.lang.CharSequence apellido;
  private java.lang.CharSequence dni;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ConductorEliminado() {}

  /**
   * All-args constructor.
   * @param keycloakId The new value for keycloakId
   * @param nombre The new value for nombre
   * @param apellido The new value for apellido
   * @param dni The new value for dni
   */
  public ConductorEliminado(java.lang.CharSequence keycloakId, java.lang.CharSequence nombre, java.lang.CharSequence apellido, java.lang.CharSequence dni) {
    this.keycloakId = keycloakId;
    this.nombre = nombre;
    this.apellido = apellido;
    this.dni = dni;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return keycloakId;
    case 1: return nombre;
    case 2: return apellido;
    case 3: return dni;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: keycloakId = (java.lang.CharSequence)value$; break;
    case 1: nombre = (java.lang.CharSequence)value$; break;
    case 2: apellido = (java.lang.CharSequence)value$; break;
    case 3: dni = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'keycloakId' field.
   * @return The value of the 'keycloakId' field.
   */
  public java.lang.CharSequence getKeycloakId() {
    return keycloakId;
  }


  /**
   * Sets the value of the 'keycloakId' field.
   * @param value the value to set.
   */
  public void setKeycloakId(java.lang.CharSequence value) {
    this.keycloakId = value;
  }

  /**
   * Gets the value of the 'nombre' field.
   * @return The value of the 'nombre' field.
   */
  public java.lang.CharSequence getNombre() {
    return nombre;
  }


  /**
   * Sets the value of the 'nombre' field.
   * @param value the value to set.
   */
  public void setNombre(java.lang.CharSequence value) {
    this.nombre = value;
  }

  /**
   * Gets the value of the 'apellido' field.
   * @return The value of the 'apellido' field.
   */
  public java.lang.CharSequence getApellido() {
    return apellido;
  }


  /**
   * Sets the value of the 'apellido' field.
   * @param value the value to set.
   */
  public void setApellido(java.lang.CharSequence value) {
    this.apellido = value;
  }

  /**
   * Gets the value of the 'dni' field.
   * @return The value of the 'dni' field.
   */
  public java.lang.CharSequence getDni() {
    return dni;
  }


  /**
   * Sets the value of the 'dni' field.
   * @param value the value to set.
   */
  public void setDni(java.lang.CharSequence value) {
    this.dni = value;
  }

  /**
   * Creates a new ConductorEliminado RecordBuilder.
   * @return A new ConductorEliminado RecordBuilder
   */
  public static com.servicioTransporte.flota.eventos.conductor.eliminar.ConductorEliminado.Builder newBuilder() {
    return new com.servicioTransporte.flota.eventos.conductor.eliminar.ConductorEliminado.Builder();
  }

  /**
   * Creates a new ConductorEliminado RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ConductorEliminado RecordBuilder
   */
  public static com.servicioTransporte.flota.eventos.conductor.eliminar.ConductorEliminado.Builder newBuilder(com.servicioTransporte.flota.eventos.conductor.eliminar.ConductorEliminado.Builder other) {
    if (other == null) {
      return new com.servicioTransporte.flota.eventos.conductor.eliminar.ConductorEliminado.Builder();
    } else {
      return new com.servicioTransporte.flota.eventos.conductor.eliminar.ConductorEliminado.Builder(other);
    }
  }

  /**
   * Creates a new ConductorEliminado RecordBuilder by copying an existing ConductorEliminado instance.
   * @param other The existing instance to copy.
   * @return A new ConductorEliminado RecordBuilder
   */
  public static com.servicioTransporte.flota.eventos.conductor.eliminar.ConductorEliminado.Builder newBuilder(com.servicioTransporte.flota.eventos.conductor.eliminar.ConductorEliminado other) {
    if (other == null) {
      return new com.servicioTransporte.flota.eventos.conductor.eliminar.ConductorEliminado.Builder();
    } else {
      return new com.servicioTransporte.flota.eventos.conductor.eliminar.ConductorEliminado.Builder(other);
    }
  }

  /**
   * RecordBuilder for ConductorEliminado instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ConductorEliminado>
    implements org.apache.avro.data.RecordBuilder<ConductorEliminado> {

    private java.lang.CharSequence keycloakId;
    private java.lang.CharSequence nombre;
    private java.lang.CharSequence apellido;
    private java.lang.CharSequence dni;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.servicioTransporte.flota.eventos.conductor.eliminar.ConductorEliminado.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.keycloakId)) {
        this.keycloakId = data().deepCopy(fields()[0].schema(), other.keycloakId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.nombre)) {
        this.nombre = data().deepCopy(fields()[1].schema(), other.nombre);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.apellido)) {
        this.apellido = data().deepCopy(fields()[2].schema(), other.apellido);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.dni)) {
        this.dni = data().deepCopy(fields()[3].schema(), other.dni);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing ConductorEliminado instance
     * @param other The existing instance to copy.
     */
    private Builder(com.servicioTransporte.flota.eventos.conductor.eliminar.ConductorEliminado other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.keycloakId)) {
        this.keycloakId = data().deepCopy(fields()[0].schema(), other.keycloakId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.nombre)) {
        this.nombre = data().deepCopy(fields()[1].schema(), other.nombre);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.apellido)) {
        this.apellido = data().deepCopy(fields()[2].schema(), other.apellido);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.dni)) {
        this.dni = data().deepCopy(fields()[3].schema(), other.dni);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'keycloakId' field.
      * @return The value.
      */
    public java.lang.CharSequence getKeycloakId() {
      return keycloakId;
    }


    /**
      * Sets the value of the 'keycloakId' field.
      * @param value The value of 'keycloakId'.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.conductor.eliminar.ConductorEliminado.Builder setKeycloakId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.keycloakId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'keycloakId' field has been set.
      * @return True if the 'keycloakId' field has been set, false otherwise.
      */
    public boolean hasKeycloakId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'keycloakId' field.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.conductor.eliminar.ConductorEliminado.Builder clearKeycloakId() {
      keycloakId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'nombre' field.
      * @return The value.
      */
    public java.lang.CharSequence getNombre() {
      return nombre;
    }


    /**
      * Sets the value of the 'nombre' field.
      * @param value The value of 'nombre'.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.conductor.eliminar.ConductorEliminado.Builder setNombre(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.nombre = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'nombre' field has been set.
      * @return True if the 'nombre' field has been set, false otherwise.
      */
    public boolean hasNombre() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'nombre' field.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.conductor.eliminar.ConductorEliminado.Builder clearNombre() {
      nombre = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'apellido' field.
      * @return The value.
      */
    public java.lang.CharSequence getApellido() {
      return apellido;
    }


    /**
      * Sets the value of the 'apellido' field.
      * @param value The value of 'apellido'.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.conductor.eliminar.ConductorEliminado.Builder setApellido(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.apellido = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'apellido' field has been set.
      * @return True if the 'apellido' field has been set, false otherwise.
      */
    public boolean hasApellido() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'apellido' field.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.conductor.eliminar.ConductorEliminado.Builder clearApellido() {
      apellido = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'dni' field.
      * @return The value.
      */
    public java.lang.CharSequence getDni() {
      return dni;
    }


    /**
      * Sets the value of the 'dni' field.
      * @param value The value of 'dni'.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.conductor.eliminar.ConductorEliminado.Builder setDni(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.dni = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'dni' field has been set.
      * @return True if the 'dni' field has been set, false otherwise.
      */
    public boolean hasDni() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'dni' field.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.conductor.eliminar.ConductorEliminado.Builder clearDni() {
      dni = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ConductorEliminado build() {
      try {
        ConductorEliminado record = new ConductorEliminado();
        record.keycloakId = fieldSetFlags()[0] ? this.keycloakId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.nombre = fieldSetFlags()[1] ? this.nombre : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.apellido = fieldSetFlags()[2] ? this.apellido : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.dni = fieldSetFlags()[3] ? this.dni : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ConductorEliminado>
    WRITER$ = (org.apache.avro.io.DatumWriter<ConductorEliminado>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ConductorEliminado>
    READER$ = (org.apache.avro.io.DatumReader<ConductorEliminado>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.keycloakId);

    out.writeString(this.nombre);

    out.writeString(this.apellido);

    out.writeString(this.dni);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.keycloakId = in.readString(this.keycloakId instanceof Utf8 ? (Utf8)this.keycloakId : null);

      this.nombre = in.readString(this.nombre instanceof Utf8 ? (Utf8)this.nombre : null);

      this.apellido = in.readString(this.apellido instanceof Utf8 ? (Utf8)this.apellido : null);

      this.dni = in.readString(this.dni instanceof Utf8 ? (Utf8)this.dni : null);

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.keycloakId = in.readString(this.keycloakId instanceof Utf8 ? (Utf8)this.keycloakId : null);
          break;

        case 1:
          this.nombre = in.readString(this.nombre instanceof Utf8 ? (Utf8)this.nombre : null);
          break;

        case 2:
          this.apellido = in.readString(this.apellido instanceof Utf8 ? (Utf8)this.apellido : null);
          break;

        case 3:
          this.dni = in.readString(this.dni instanceof Utf8 ? (Utf8)this.dni : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










