/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.servicioTransporte.flota.eventos.vehiculo.seguimiento;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Evento de telemetría en tiempo real enviado por el vehículo */
@org.apache.avro.specific.AvroGenerated
public class TelemetriaVehiculo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3166710212465692483L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TelemetriaVehiculo\",\"namespace\":\"com.servicioTransporte.flota.eventos.vehiculo.seguimiento\",\"doc\":\"Evento de telemetría en tiempo real enviado por el vehículo\",\"fields\":[{\"name\":\"vehicleId\",\"type\":\"string\",\"doc\":\"VIN o Placa\"},{\"name\":\"latitude\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"longitude\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"speed\",\"type\":[\"null\",\"double\"],\"doc\":\"Velocidad en km/h\",\"default\":null},{\"name\":\"batteryLevel\",\"type\":[\"null\",\"double\"],\"doc\":\"Porcentaje 0-100\",\"default\":null},{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"additionalData\",\"type\":[\"null\",{\"type\":\"map\",\"values\":\"string\"}],\"doc\":\"Mapa para datos adicionales no estructurados\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<TelemetriaVehiculo> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TelemetriaVehiculo> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TelemetriaVehiculo> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TelemetriaVehiculo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TelemetriaVehiculo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TelemetriaVehiculo to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TelemetriaVehiculo from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TelemetriaVehiculo instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TelemetriaVehiculo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** VIN o Placa */
  private java.lang.CharSequence vehicleId;
  private java.lang.Double latitude;
  private java.lang.Double longitude;
  /** Velocidad en km/h */
  private java.lang.Double speed;
  /** Porcentaje 0-100 */
  private java.lang.Double batteryLevel;
  private java.time.Instant timestamp;
  /** Mapa para datos adicionales no estructurados */
  private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> additionalData;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TelemetriaVehiculo() {}

  /**
   * All-args constructor.
   * @param vehicleId VIN o Placa
   * @param latitude The new value for latitude
   * @param longitude The new value for longitude
   * @param speed Velocidad en km/h
   * @param batteryLevel Porcentaje 0-100
   * @param timestamp The new value for timestamp
   * @param additionalData Mapa para datos adicionales no estructurados
   */
  public TelemetriaVehiculo(java.lang.CharSequence vehicleId, java.lang.Double latitude, java.lang.Double longitude, java.lang.Double speed, java.lang.Double batteryLevel, java.time.Instant timestamp, java.util.Map<java.lang.CharSequence,java.lang.CharSequence> additionalData) {
    this.vehicleId = vehicleId;
    this.latitude = latitude;
    this.longitude = longitude;
    this.speed = speed;
    this.batteryLevel = batteryLevel;
    this.timestamp = timestamp.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.additionalData = additionalData;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return vehicleId;
    case 1: return latitude;
    case 2: return longitude;
    case 3: return speed;
    case 4: return batteryLevel;
    case 5: return timestamp;
    case 6: return additionalData;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: vehicleId = (java.lang.CharSequence)value$; break;
    case 1: latitude = (java.lang.Double)value$; break;
    case 2: longitude = (java.lang.Double)value$; break;
    case 3: speed = (java.lang.Double)value$; break;
    case 4: batteryLevel = (java.lang.Double)value$; break;
    case 5: timestamp = (java.time.Instant)value$; break;
    case 6: additionalData = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'vehicleId' field.
   * @return VIN o Placa
   */
  public java.lang.CharSequence getVehicleId() {
    return vehicleId;
  }


  /**
   * Sets the value of the 'vehicleId' field.
   * VIN o Placa
   * @param value the value to set.
   */
  public void setVehicleId(java.lang.CharSequence value) {
    this.vehicleId = value;
  }

  /**
   * Gets the value of the 'latitude' field.
   * @return The value of the 'latitude' field.
   */
  public java.lang.Double getLatitude() {
    return latitude;
  }


  /**
   * Sets the value of the 'latitude' field.
   * @param value the value to set.
   */
  public void setLatitude(java.lang.Double value) {
    this.latitude = value;
  }

  /**
   * Gets the value of the 'longitude' field.
   * @return The value of the 'longitude' field.
   */
  public java.lang.Double getLongitude() {
    return longitude;
  }


  /**
   * Sets the value of the 'longitude' field.
   * @param value the value to set.
   */
  public void setLongitude(java.lang.Double value) {
    this.longitude = value;
  }

  /**
   * Gets the value of the 'speed' field.
   * @return Velocidad en km/h
   */
  public java.lang.Double getSpeed() {
    return speed;
  }


  /**
   * Sets the value of the 'speed' field.
   * Velocidad en km/h
   * @param value the value to set.
   */
  public void setSpeed(java.lang.Double value) {
    this.speed = value;
  }

  /**
   * Gets the value of the 'batteryLevel' field.
   * @return Porcentaje 0-100
   */
  public java.lang.Double getBatteryLevel() {
    return batteryLevel;
  }


  /**
   * Sets the value of the 'batteryLevel' field.
   * Porcentaje 0-100
   * @param value the value to set.
   */
  public void setBatteryLevel(java.lang.Double value) {
    this.batteryLevel = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.time.Instant getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.time.Instant value) {
    this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'additionalData' field.
   * @return Mapa para datos adicionales no estructurados
   */
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getAdditionalData() {
    return additionalData;
  }


  /**
   * Sets the value of the 'additionalData' field.
   * Mapa para datos adicionales no estructurados
   * @param value the value to set.
   */
  public void setAdditionalData(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
    this.additionalData = value;
  }

  /**
   * Creates a new TelemetriaVehiculo RecordBuilder.
   * @return A new TelemetriaVehiculo RecordBuilder
   */
  public static com.servicioTransporte.flota.eventos.vehiculo.seguimiento.TelemetriaVehiculo.Builder newBuilder() {
    return new com.servicioTransporte.flota.eventos.vehiculo.seguimiento.TelemetriaVehiculo.Builder();
  }

  /**
   * Creates a new TelemetriaVehiculo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TelemetriaVehiculo RecordBuilder
   */
  public static com.servicioTransporte.flota.eventos.vehiculo.seguimiento.TelemetriaVehiculo.Builder newBuilder(com.servicioTransporte.flota.eventos.vehiculo.seguimiento.TelemetriaVehiculo.Builder other) {
    if (other == null) {
      return new com.servicioTransporte.flota.eventos.vehiculo.seguimiento.TelemetriaVehiculo.Builder();
    } else {
      return new com.servicioTransporte.flota.eventos.vehiculo.seguimiento.TelemetriaVehiculo.Builder(other);
    }
  }

  /**
   * Creates a new TelemetriaVehiculo RecordBuilder by copying an existing TelemetriaVehiculo instance.
   * @param other The existing instance to copy.
   * @return A new TelemetriaVehiculo RecordBuilder
   */
  public static com.servicioTransporte.flota.eventos.vehiculo.seguimiento.TelemetriaVehiculo.Builder newBuilder(com.servicioTransporte.flota.eventos.vehiculo.seguimiento.TelemetriaVehiculo other) {
    if (other == null) {
      return new com.servicioTransporte.flota.eventos.vehiculo.seguimiento.TelemetriaVehiculo.Builder();
    } else {
      return new com.servicioTransporte.flota.eventos.vehiculo.seguimiento.TelemetriaVehiculo.Builder(other);
    }
  }

  /**
   * RecordBuilder for TelemetriaVehiculo instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TelemetriaVehiculo>
    implements org.apache.avro.data.RecordBuilder<TelemetriaVehiculo> {

    /** VIN o Placa */
    private java.lang.CharSequence vehicleId;
    private java.lang.Double latitude;
    private java.lang.Double longitude;
    /** Velocidad en km/h */
    private java.lang.Double speed;
    /** Porcentaje 0-100 */
    private java.lang.Double batteryLevel;
    private java.time.Instant timestamp;
    /** Mapa para datos adicionales no estructurados */
    private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> additionalData;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.servicioTransporte.flota.eventos.vehiculo.seguimiento.TelemetriaVehiculo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.vehicleId)) {
        this.vehicleId = data().deepCopy(fields()[0].schema(), other.vehicleId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.latitude)) {
        this.latitude = data().deepCopy(fields()[1].schema(), other.latitude);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.longitude)) {
        this.longitude = data().deepCopy(fields()[2].schema(), other.longitude);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.speed)) {
        this.speed = data().deepCopy(fields()[3].schema(), other.speed);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.batteryLevel)) {
        this.batteryLevel = data().deepCopy(fields()[4].schema(), other.batteryLevel);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[5].schema(), other.timestamp);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.additionalData)) {
        this.additionalData = data().deepCopy(fields()[6].schema(), other.additionalData);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing TelemetriaVehiculo instance
     * @param other The existing instance to copy.
     */
    private Builder(com.servicioTransporte.flota.eventos.vehiculo.seguimiento.TelemetriaVehiculo other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.vehicleId)) {
        this.vehicleId = data().deepCopy(fields()[0].schema(), other.vehicleId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.latitude)) {
        this.latitude = data().deepCopy(fields()[1].schema(), other.latitude);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.longitude)) {
        this.longitude = data().deepCopy(fields()[2].schema(), other.longitude);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.speed)) {
        this.speed = data().deepCopy(fields()[3].schema(), other.speed);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.batteryLevel)) {
        this.batteryLevel = data().deepCopy(fields()[4].schema(), other.batteryLevel);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[5].schema(), other.timestamp);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.additionalData)) {
        this.additionalData = data().deepCopy(fields()[6].schema(), other.additionalData);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'vehicleId' field.
      * VIN o Placa
      * @return The value.
      */
    public java.lang.CharSequence getVehicleId() {
      return vehicleId;
    }


    /**
      * Sets the value of the 'vehicleId' field.
      * VIN o Placa
      * @param value The value of 'vehicleId'.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.vehiculo.seguimiento.TelemetriaVehiculo.Builder setVehicleId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.vehicleId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'vehicleId' field has been set.
      * VIN o Placa
      * @return True if the 'vehicleId' field has been set, false otherwise.
      */
    public boolean hasVehicleId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'vehicleId' field.
      * VIN o Placa
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.vehiculo.seguimiento.TelemetriaVehiculo.Builder clearVehicleId() {
      vehicleId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'latitude' field.
      * @return The value.
      */
    public java.lang.Double getLatitude() {
      return latitude;
    }


    /**
      * Sets the value of the 'latitude' field.
      * @param value The value of 'latitude'.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.vehiculo.seguimiento.TelemetriaVehiculo.Builder setLatitude(java.lang.Double value) {
      validate(fields()[1], value);
      this.latitude = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'latitude' field has been set.
      * @return True if the 'latitude' field has been set, false otherwise.
      */
    public boolean hasLatitude() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'latitude' field.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.vehiculo.seguimiento.TelemetriaVehiculo.Builder clearLatitude() {
      latitude = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'longitude' field.
      * @return The value.
      */
    public java.lang.Double getLongitude() {
      return longitude;
    }


    /**
      * Sets the value of the 'longitude' field.
      * @param value The value of 'longitude'.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.vehiculo.seguimiento.TelemetriaVehiculo.Builder setLongitude(java.lang.Double value) {
      validate(fields()[2], value);
      this.longitude = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'longitude' field has been set.
      * @return True if the 'longitude' field has been set, false otherwise.
      */
    public boolean hasLongitude() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'longitude' field.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.vehiculo.seguimiento.TelemetriaVehiculo.Builder clearLongitude() {
      longitude = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'speed' field.
      * Velocidad en km/h
      * @return The value.
      */
    public java.lang.Double getSpeed() {
      return speed;
    }


    /**
      * Sets the value of the 'speed' field.
      * Velocidad en km/h
      * @param value The value of 'speed'.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.vehiculo.seguimiento.TelemetriaVehiculo.Builder setSpeed(java.lang.Double value) {
      validate(fields()[3], value);
      this.speed = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'speed' field has been set.
      * Velocidad en km/h
      * @return True if the 'speed' field has been set, false otherwise.
      */
    public boolean hasSpeed() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'speed' field.
      * Velocidad en km/h
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.vehiculo.seguimiento.TelemetriaVehiculo.Builder clearSpeed() {
      speed = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'batteryLevel' field.
      * Porcentaje 0-100
      * @return The value.
      */
    public java.lang.Double getBatteryLevel() {
      return batteryLevel;
    }


    /**
      * Sets the value of the 'batteryLevel' field.
      * Porcentaje 0-100
      * @param value The value of 'batteryLevel'.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.vehiculo.seguimiento.TelemetriaVehiculo.Builder setBatteryLevel(java.lang.Double value) {
      validate(fields()[4], value);
      this.batteryLevel = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'batteryLevel' field has been set.
      * Porcentaje 0-100
      * @return True if the 'batteryLevel' field has been set, false otherwise.
      */
    public boolean hasBatteryLevel() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'batteryLevel' field.
      * Porcentaje 0-100
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.vehiculo.seguimiento.TelemetriaVehiculo.Builder clearBatteryLevel() {
      batteryLevel = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.time.Instant getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.vehiculo.seguimiento.TelemetriaVehiculo.Builder setTimestamp(java.time.Instant value) {
      validate(fields()[5], value);
      this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.vehiculo.seguimiento.TelemetriaVehiculo.Builder clearTimestamp() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'additionalData' field.
      * Mapa para datos adicionales no estructurados
      * @return The value.
      */
    public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getAdditionalData() {
      return additionalData;
    }


    /**
      * Sets the value of the 'additionalData' field.
      * Mapa para datos adicionales no estructurados
      * @param value The value of 'additionalData'.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.vehiculo.seguimiento.TelemetriaVehiculo.Builder setAdditionalData(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
      validate(fields()[6], value);
      this.additionalData = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'additionalData' field has been set.
      * Mapa para datos adicionales no estructurados
      * @return True if the 'additionalData' field has been set, false otherwise.
      */
    public boolean hasAdditionalData() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'additionalData' field.
      * Mapa para datos adicionales no estructurados
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.vehiculo.seguimiento.TelemetriaVehiculo.Builder clearAdditionalData() {
      additionalData = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TelemetriaVehiculo build() {
      try {
        TelemetriaVehiculo record = new TelemetriaVehiculo();
        record.vehicleId = fieldSetFlags()[0] ? this.vehicleId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.latitude = fieldSetFlags()[1] ? this.latitude : (java.lang.Double) defaultValue(fields()[1]);
        record.longitude = fieldSetFlags()[2] ? this.longitude : (java.lang.Double) defaultValue(fields()[2]);
        record.speed = fieldSetFlags()[3] ? this.speed : (java.lang.Double) defaultValue(fields()[3]);
        record.batteryLevel = fieldSetFlags()[4] ? this.batteryLevel : (java.lang.Double) defaultValue(fields()[4]);
        record.timestamp = fieldSetFlags()[5] ? this.timestamp : (java.time.Instant) defaultValue(fields()[5]);
        record.additionalData = fieldSetFlags()[6] ? this.additionalData : (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TelemetriaVehiculo>
    WRITER$ = (org.apache.avro.io.DatumWriter<TelemetriaVehiculo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TelemetriaVehiculo>
    READER$ = (org.apache.avro.io.DatumReader<TelemetriaVehiculo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










