/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.servicioTransporte.flota.eventos.conductor.registro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RegistroConductorFallido extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6340676438098100418L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RegistroConductorFallido\",\"namespace\":\"com.servicioTransporte.flota.eventos.conductor.registro\",\"fields\":[{\"name\":\"keycloakId\",\"type\":\"string\"},{\"name\":\"error\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RegistroConductorFallido> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RegistroConductorFallido> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RegistroConductorFallido> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RegistroConductorFallido> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RegistroConductorFallido> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RegistroConductorFallido to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RegistroConductorFallido from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RegistroConductorFallido instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RegistroConductorFallido fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence keycloakId;
  private java.lang.CharSequence error;
  private long timestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RegistroConductorFallido() {}

  /**
   * All-args constructor.
   * @param keycloakId The new value for keycloakId
   * @param error The new value for error
   * @param timestamp The new value for timestamp
   */
  public RegistroConductorFallido(java.lang.CharSequence keycloakId, java.lang.CharSequence error, java.lang.Long timestamp) {
    this.keycloakId = keycloakId;
    this.error = error;
    this.timestamp = timestamp;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return keycloakId;
    case 1: return error;
    case 2: return timestamp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: keycloakId = (java.lang.CharSequence)value$; break;
    case 1: error = (java.lang.CharSequence)value$; break;
    case 2: timestamp = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'keycloakId' field.
   * @return The value of the 'keycloakId' field.
   */
  public java.lang.CharSequence getKeycloakId() {
    return keycloakId;
  }


  /**
   * Sets the value of the 'keycloakId' field.
   * @param value the value to set.
   */
  public void setKeycloakId(java.lang.CharSequence value) {
    this.keycloakId = value;
  }

  /**
   * Gets the value of the 'error' field.
   * @return The value of the 'error' field.
   */
  public java.lang.CharSequence getError() {
    return error;
  }


  /**
   * Sets the value of the 'error' field.
   * @param value the value to set.
   */
  public void setError(java.lang.CharSequence value) {
    this.error = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Creates a new RegistroConductorFallido RecordBuilder.
   * @return A new RegistroConductorFallido RecordBuilder
   */
  public static com.servicioTransporte.flota.eventos.conductor.registro.RegistroConductorFallido.Builder newBuilder() {
    return new com.servicioTransporte.flota.eventos.conductor.registro.RegistroConductorFallido.Builder();
  }

  /**
   * Creates a new RegistroConductorFallido RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RegistroConductorFallido RecordBuilder
   */
  public static com.servicioTransporte.flota.eventos.conductor.registro.RegistroConductorFallido.Builder newBuilder(com.servicioTransporte.flota.eventos.conductor.registro.RegistroConductorFallido.Builder other) {
    if (other == null) {
      return new com.servicioTransporte.flota.eventos.conductor.registro.RegistroConductorFallido.Builder();
    } else {
      return new com.servicioTransporte.flota.eventos.conductor.registro.RegistroConductorFallido.Builder(other);
    }
  }

  /**
   * Creates a new RegistroConductorFallido RecordBuilder by copying an existing RegistroConductorFallido instance.
   * @param other The existing instance to copy.
   * @return A new RegistroConductorFallido RecordBuilder
   */
  public static com.servicioTransporte.flota.eventos.conductor.registro.RegistroConductorFallido.Builder newBuilder(com.servicioTransporte.flota.eventos.conductor.registro.RegistroConductorFallido other) {
    if (other == null) {
      return new com.servicioTransporte.flota.eventos.conductor.registro.RegistroConductorFallido.Builder();
    } else {
      return new com.servicioTransporte.flota.eventos.conductor.registro.RegistroConductorFallido.Builder(other);
    }
  }

  /**
   * RecordBuilder for RegistroConductorFallido instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RegistroConductorFallido>
    implements org.apache.avro.data.RecordBuilder<RegistroConductorFallido> {

    private java.lang.CharSequence keycloakId;
    private java.lang.CharSequence error;
    private long timestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.servicioTransporte.flota.eventos.conductor.registro.RegistroConductorFallido.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.keycloakId)) {
        this.keycloakId = data().deepCopy(fields()[0].schema(), other.keycloakId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.error)) {
        this.error = data().deepCopy(fields()[1].schema(), other.error);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[2].schema(), other.timestamp);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing RegistroConductorFallido instance
     * @param other The existing instance to copy.
     */
    private Builder(com.servicioTransporte.flota.eventos.conductor.registro.RegistroConductorFallido other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.keycloakId)) {
        this.keycloakId = data().deepCopy(fields()[0].schema(), other.keycloakId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.error)) {
        this.error = data().deepCopy(fields()[1].schema(), other.error);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[2].schema(), other.timestamp);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'keycloakId' field.
      * @return The value.
      */
    public java.lang.CharSequence getKeycloakId() {
      return keycloakId;
    }


    /**
      * Sets the value of the 'keycloakId' field.
      * @param value The value of 'keycloakId'.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.conductor.registro.RegistroConductorFallido.Builder setKeycloakId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.keycloakId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'keycloakId' field has been set.
      * @return True if the 'keycloakId' field has been set, false otherwise.
      */
    public boolean hasKeycloakId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'keycloakId' field.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.conductor.registro.RegistroConductorFallido.Builder clearKeycloakId() {
      keycloakId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'error' field.
      * @return The value.
      */
    public java.lang.CharSequence getError() {
      return error;
    }


    /**
      * Sets the value of the 'error' field.
      * @param value The value of 'error'.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.conductor.registro.RegistroConductorFallido.Builder setError(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.error = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'error' field has been set.
      * @return True if the 'error' field has been set, false otherwise.
      */
    public boolean hasError() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'error' field.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.conductor.registro.RegistroConductorFallido.Builder clearError() {
      error = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.conductor.registro.RegistroConductorFallido.Builder setTimestamp(long value) {
      validate(fields()[2], value);
      this.timestamp = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.conductor.registro.RegistroConductorFallido.Builder clearTimestamp() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RegistroConductorFallido build() {
      try {
        RegistroConductorFallido record = new RegistroConductorFallido();
        record.keycloakId = fieldSetFlags()[0] ? this.keycloakId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.error = fieldSetFlags()[1] ? this.error : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.timestamp = fieldSetFlags()[2] ? this.timestamp : (java.lang.Long) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RegistroConductorFallido>
    WRITER$ = (org.apache.avro.io.DatumWriter<RegistroConductorFallido>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RegistroConductorFallido>
    READER$ = (org.apache.avro.io.DatumReader<RegistroConductorFallido>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.keycloakId);

    out.writeString(this.error);

    out.writeLong(this.timestamp);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.keycloakId = in.readString(this.keycloakId instanceof Utf8 ? (Utf8)this.keycloakId : null);

      this.error = in.readString(this.error instanceof Utf8 ? (Utf8)this.error : null);

      this.timestamp = in.readLong();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.keycloakId = in.readString(this.keycloakId instanceof Utf8 ? (Utf8)this.keycloakId : null);
          break;

        case 1:
          this.error = in.readString(this.error instanceof Utf8 ? (Utf8)this.error : null);
          break;

        case 2:
          this.timestamp = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










