/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.servicioTransporte.flota.eventos.conductor.registro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RegistroConductorIniciado extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2175803008874866593L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RegistroConductorIniciado\",\"namespace\":\"com.servicioTransporte.flota.eventos.conductor\",\"fields\":[{\"name\":\"keycloakId\",\"type\":\"string\"},{\"name\":\"nombre\",\"type\":\"string\"},{\"name\":\"apellido\",\"type\":\"string\"},{\"name\":\"dni\",\"type\":\"string\"},{\"name\":\"categoriasLicencia\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RegistroConductorIniciado> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RegistroConductorIniciado> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RegistroConductorIniciado> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RegistroConductorIniciado> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RegistroConductorIniciado> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RegistroConductorIniciado to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RegistroConductorIniciado from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RegistroConductorIniciado instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RegistroConductorIniciado fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence keycloakId;
  private java.lang.CharSequence nombre;
  private java.lang.CharSequence apellido;
  private java.lang.CharSequence dni;
  private java.util.List<java.lang.CharSequence> categoriasLicencia;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RegistroConductorIniciado() {}

  /**
   * All-args constructor.
   * @param keycloakId The new value for keycloakId
   * @param nombre The new value for nombre
   * @param apellido The new value for apellido
   * @param dni The new value for dni
   * @param categoriasLicencia The new value for categoriasLicencia
   */
  public RegistroConductorIniciado(java.lang.CharSequence keycloakId, java.lang.CharSequence nombre, java.lang.CharSequence apellido, java.lang.CharSequence dni, java.util.List<java.lang.CharSequence> categoriasLicencia) {
    this.keycloakId = keycloakId;
    this.nombre = nombre;
    this.apellido = apellido;
    this.dni = dni;
    this.categoriasLicencia = categoriasLicencia;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return keycloakId;
    case 1: return nombre;
    case 2: return apellido;
    case 3: return dni;
    case 4: return categoriasLicencia;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: keycloakId = (java.lang.CharSequence)value$; break;
    case 1: nombre = (java.lang.CharSequence)value$; break;
    case 2: apellido = (java.lang.CharSequence)value$; break;
    case 3: dni = (java.lang.CharSequence)value$; break;
    case 4: categoriasLicencia = (java.util.List<java.lang.CharSequence>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'keycloakId' field.
   * @return The value of the 'keycloakId' field.
   */
  public java.lang.CharSequence getKeycloakId() {
    return keycloakId;
  }


  /**
   * Sets the value of the 'keycloakId' field.
   * @param value the value to set.
   */
  public void setKeycloakId(java.lang.CharSequence value) {
    this.keycloakId = value;
  }

  /**
   * Gets the value of the 'nombre' field.
   * @return The value of the 'nombre' field.
   */
  public java.lang.CharSequence getNombre() {
    return nombre;
  }


  /**
   * Sets the value of the 'nombre' field.
   * @param value the value to set.
   */
  public void setNombre(java.lang.CharSequence value) {
    this.nombre = value;
  }

  /**
   * Gets the value of the 'apellido' field.
   * @return The value of the 'apellido' field.
   */
  public java.lang.CharSequence getApellido() {
    return apellido;
  }


  /**
   * Sets the value of the 'apellido' field.
   * @param value the value to set.
   */
  public void setApellido(java.lang.CharSequence value) {
    this.apellido = value;
  }

  /**
   * Gets the value of the 'dni' field.
   * @return The value of the 'dni' field.
   */
  public java.lang.CharSequence getDni() {
    return dni;
  }


  /**
   * Sets the value of the 'dni' field.
   * @param value the value to set.
   */
  public void setDni(java.lang.CharSequence value) {
    this.dni = value;
  }

  /**
   * Gets the value of the 'categoriasLicencia' field.
   * @return The value of the 'categoriasLicencia' field.
   */
  public java.util.List<java.lang.CharSequence> getCategoriasLicencia() {
    return categoriasLicencia;
  }


  /**
   * Sets the value of the 'categoriasLicencia' field.
   * @param value the value to set.
   */
  public void setCategoriasLicencia(java.util.List<java.lang.CharSequence> value) {
    this.categoriasLicencia = value;
  }

  /**
   * Creates a new RegistroConductorIniciado RecordBuilder.
   * @return A new RegistroConductorIniciado RecordBuilder
   */
  public static RegistroConductorIniciado.Builder newBuilder() {
    return new RegistroConductorIniciado.Builder();
  }

  /**
   * Creates a new RegistroConductorIniciado RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RegistroConductorIniciado RecordBuilder
   */
  public static RegistroConductorIniciado.Builder newBuilder(RegistroConductorIniciado.Builder other) {
    if (other == null) {
      return new RegistroConductorIniciado.Builder();
    } else {
      return new RegistroConductorIniciado.Builder(other);
    }
  }

  /**
   * Creates a new RegistroConductorIniciado RecordBuilder by copying an existing RegistroConductorIniciado instance.
   * @param other The existing instance to copy.
   * @return A new RegistroConductorIniciado RecordBuilder
   */
  public static RegistroConductorIniciado.Builder newBuilder(RegistroConductorIniciado other) {
    if (other == null) {
      return new RegistroConductorIniciado.Builder();
    } else {
      return new RegistroConductorIniciado.Builder(other);
    }
  }

  /**
   * RecordBuilder for RegistroConductorIniciado instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RegistroConductorIniciado>
    implements org.apache.avro.data.RecordBuilder<RegistroConductorIniciado> {

    private java.lang.CharSequence keycloakId;
    private java.lang.CharSequence nombre;
    private java.lang.CharSequence apellido;
    private java.lang.CharSequence dni;
    private java.util.List<java.lang.CharSequence> categoriasLicencia;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(RegistroConductorIniciado.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.keycloakId)) {
        this.keycloakId = data().deepCopy(fields()[0].schema(), other.keycloakId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.nombre)) {
        this.nombre = data().deepCopy(fields()[1].schema(), other.nombre);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.apellido)) {
        this.apellido = data().deepCopy(fields()[2].schema(), other.apellido);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.dni)) {
        this.dni = data().deepCopy(fields()[3].schema(), other.dni);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.categoriasLicencia)) {
        this.categoriasLicencia = data().deepCopy(fields()[4].schema(), other.categoriasLicencia);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing RegistroConductorIniciado instance
     * @param other The existing instance to copy.
     */
    private Builder(RegistroConductorIniciado other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.keycloakId)) {
        this.keycloakId = data().deepCopy(fields()[0].schema(), other.keycloakId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.nombre)) {
        this.nombre = data().deepCopy(fields()[1].schema(), other.nombre);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.apellido)) {
        this.apellido = data().deepCopy(fields()[2].schema(), other.apellido);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.dni)) {
        this.dni = data().deepCopy(fields()[3].schema(), other.dni);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.categoriasLicencia)) {
        this.categoriasLicencia = data().deepCopy(fields()[4].schema(), other.categoriasLicencia);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'keycloakId' field.
      * @return The value.
      */
    public java.lang.CharSequence getKeycloakId() {
      return keycloakId;
    }


    /**
      * Sets the value of the 'keycloakId' field.
      * @param value The value of 'keycloakId'.
      * @return This builder.
      */
    public RegistroConductorIniciado.Builder setKeycloakId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.keycloakId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'keycloakId' field has been set.
      * @return True if the 'keycloakId' field has been set, false otherwise.
      */
    public boolean hasKeycloakId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'keycloakId' field.
      * @return This builder.
      */
    public RegistroConductorIniciado.Builder clearKeycloakId() {
      keycloakId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'nombre' field.
      * @return The value.
      */
    public java.lang.CharSequence getNombre() {
      return nombre;
    }


    /**
      * Sets the value of the 'nombre' field.
      * @param value The value of 'nombre'.
      * @return This builder.
      */
    public RegistroConductorIniciado.Builder setNombre(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.nombre = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'nombre' field has been set.
      * @return True if the 'nombre' field has been set, false otherwise.
      */
    public boolean hasNombre() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'nombre' field.
      * @return This builder.
      */
    public RegistroConductorIniciado.Builder clearNombre() {
      nombre = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'apellido' field.
      * @return The value.
      */
    public java.lang.CharSequence getApellido() {
      return apellido;
    }


    /**
      * Sets the value of the 'apellido' field.
      * @param value The value of 'apellido'.
      * @return This builder.
      */
    public RegistroConductorIniciado.Builder setApellido(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.apellido = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'apellido' field has been set.
      * @return True if the 'apellido' field has been set, false otherwise.
      */
    public boolean hasApellido() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'apellido' field.
      * @return This builder.
      */
    public RegistroConductorIniciado.Builder clearApellido() {
      apellido = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'dni' field.
      * @return The value.
      */
    public java.lang.CharSequence getDni() {
      return dni;
    }


    /**
      * Sets the value of the 'dni' field.
      * @param value The value of 'dni'.
      * @return This builder.
      */
    public RegistroConductorIniciado.Builder setDni(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.dni = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'dni' field has been set.
      * @return True if the 'dni' field has been set, false otherwise.
      */
    public boolean hasDni() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'dni' field.
      * @return This builder.
      */
    public RegistroConductorIniciado.Builder clearDni() {
      dni = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'categoriasLicencia' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getCategoriasLicencia() {
      return categoriasLicencia;
    }


    /**
      * Sets the value of the 'categoriasLicencia' field.
      * @param value The value of 'categoriasLicencia'.
      * @return This builder.
      */
    public RegistroConductorIniciado.Builder setCategoriasLicencia(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[4], value);
      this.categoriasLicencia = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'categoriasLicencia' field has been set.
      * @return True if the 'categoriasLicencia' field has been set, false otherwise.
      */
    public boolean hasCategoriasLicencia() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'categoriasLicencia' field.
      * @return This builder.
      */
    public RegistroConductorIniciado.Builder clearCategoriasLicencia() {
      categoriasLicencia = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RegistroConductorIniciado build() {
      try {
        RegistroConductorIniciado record = new RegistroConductorIniciado();
        record.keycloakId = fieldSetFlags()[0] ? this.keycloakId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.nombre = fieldSetFlags()[1] ? this.nombre : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.apellido = fieldSetFlags()[2] ? this.apellido : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.dni = fieldSetFlags()[3] ? this.dni : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.categoriasLicencia = fieldSetFlags()[4] ? this.categoriasLicencia : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RegistroConductorIniciado>
    WRITER$ = (org.apache.avro.io.DatumWriter<RegistroConductorIniciado>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RegistroConductorIniciado>
    READER$ = (org.apache.avro.io.DatumReader<RegistroConductorIniciado>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.keycloakId);

    out.writeString(this.nombre);

    out.writeString(this.apellido);

    out.writeString(this.dni);

    long size0 = this.categoriasLicencia.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.CharSequence e0: this.categoriasLicencia) {
      actualSize0++;
      out.startItem();
      out.writeString(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.keycloakId = in.readString(this.keycloakId instanceof Utf8 ? (Utf8)this.keycloakId : null);

      this.nombre = in.readString(this.nombre instanceof Utf8 ? (Utf8)this.nombre : null);

      this.apellido = in.readString(this.apellido instanceof Utf8 ? (Utf8)this.apellido : null);

      this.dni = in.readString(this.dni instanceof Utf8 ? (Utf8)this.dni : null);

      long size0 = in.readArrayStart();
      java.util.List<java.lang.CharSequence> a0 = this.categoriasLicencia;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("categoriasLicencia").schema());
        this.categoriasLicencia = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.keycloakId = in.readString(this.keycloakId instanceof Utf8 ? (Utf8)this.keycloakId : null);
          break;

        case 1:
          this.nombre = in.readString(this.nombre instanceof Utf8 ? (Utf8)this.nombre : null);
          break;

        case 2:
          this.apellido = in.readString(this.apellido instanceof Utf8 ? (Utf8)this.apellido : null);
          break;

        case 3:
          this.dni = in.readString(this.dni instanceof Utf8 ? (Utf8)this.dni : null);
          break;

        case 4:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.CharSequence> a0 = this.categoriasLicencia;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("categoriasLicencia").schema());
            this.categoriasLicencia = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










