/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.servicioTransporte.flota.eventos.conductor.registro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class UsuarioConductorCreado extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8733184628050966425L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UsuarioConductorCreado\",\"namespace\":\"com.servicioTransporte.flota.eventos.conductor.registro\",\"fields\":[{\"name\":\"conductorId\",\"type\":\"long\"},{\"name\":\"keycloakUserId\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<UsuarioConductorCreado> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UsuarioConductorCreado> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<UsuarioConductorCreado> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<UsuarioConductorCreado> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<UsuarioConductorCreado> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this UsuarioConductorCreado to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a UsuarioConductorCreado from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a UsuarioConductorCreado instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static UsuarioConductorCreado fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long conductorId;
  private java.lang.CharSequence keycloakUserId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UsuarioConductorCreado() {}

  /**
   * All-args constructor.
   * @param conductorId The new value for conductorId
   * @param keycloakUserId The new value for keycloakUserId
   */
  public UsuarioConductorCreado(java.lang.Long conductorId, java.lang.CharSequence keycloakUserId) {
    this.conductorId = conductorId;
    this.keycloakUserId = keycloakUserId;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return conductorId;
    case 1: return keycloakUserId;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: conductorId = (java.lang.Long)value$; break;
    case 1: keycloakUserId = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'conductorId' field.
   * @return The value of the 'conductorId' field.
   */
  public long getConductorId() {
    return conductorId;
  }


  /**
   * Sets the value of the 'conductorId' field.
   * @param value the value to set.
   */
  public void setConductorId(long value) {
    this.conductorId = value;
  }

  /**
   * Gets the value of the 'keycloakUserId' field.
   * @return The value of the 'keycloakUserId' field.
   */
  public java.lang.CharSequence getKeycloakUserId() {
    return keycloakUserId;
  }


  /**
   * Sets the value of the 'keycloakUserId' field.
   * @param value the value to set.
   */
  public void setKeycloakUserId(java.lang.CharSequence value) {
    this.keycloakUserId = value;
  }

  /**
   * Creates a new UsuarioConductorCreado RecordBuilder.
   * @return A new UsuarioConductorCreado RecordBuilder
   */
  public static com.servicioTransporte.flota.eventos.conductor.registro.UsuarioConductorCreado.Builder newBuilder() {
    return new com.servicioTransporte.flota.eventos.conductor.registro.UsuarioConductorCreado.Builder();
  }

  /**
   * Creates a new UsuarioConductorCreado RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UsuarioConductorCreado RecordBuilder
   */
  public static com.servicioTransporte.flota.eventos.conductor.registro.UsuarioConductorCreado.Builder newBuilder(com.servicioTransporte.flota.eventos.conductor.registro.UsuarioConductorCreado.Builder other) {
    if (other == null) {
      return new com.servicioTransporte.flota.eventos.conductor.registro.UsuarioConductorCreado.Builder();
    } else {
      return new com.servicioTransporte.flota.eventos.conductor.registro.UsuarioConductorCreado.Builder(other);
    }
  }

  /**
   * Creates a new UsuarioConductorCreado RecordBuilder by copying an existing UsuarioConductorCreado instance.
   * @param other The existing instance to copy.
   * @return A new UsuarioConductorCreado RecordBuilder
   */
  public static com.servicioTransporte.flota.eventos.conductor.registro.UsuarioConductorCreado.Builder newBuilder(com.servicioTransporte.flota.eventos.conductor.registro.UsuarioConductorCreado other) {
    if (other == null) {
      return new com.servicioTransporte.flota.eventos.conductor.registro.UsuarioConductorCreado.Builder();
    } else {
      return new com.servicioTransporte.flota.eventos.conductor.registro.UsuarioConductorCreado.Builder(other);
    }
  }

  /**
   * RecordBuilder for UsuarioConductorCreado instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UsuarioConductorCreado>
    implements org.apache.avro.data.RecordBuilder<UsuarioConductorCreado> {

    private long conductorId;
    private java.lang.CharSequence keycloakUserId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.servicioTransporte.flota.eventos.conductor.registro.UsuarioConductorCreado.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.conductorId)) {
        this.conductorId = data().deepCopy(fields()[0].schema(), other.conductorId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.keycloakUserId)) {
        this.keycloakUserId = data().deepCopy(fields()[1].schema(), other.keycloakUserId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing UsuarioConductorCreado instance
     * @param other The existing instance to copy.
     */
    private Builder(com.servicioTransporte.flota.eventos.conductor.registro.UsuarioConductorCreado other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.conductorId)) {
        this.conductorId = data().deepCopy(fields()[0].schema(), other.conductorId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.keycloakUserId)) {
        this.keycloakUserId = data().deepCopy(fields()[1].schema(), other.keycloakUserId);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'conductorId' field.
      * @return The value.
      */
    public long getConductorId() {
      return conductorId;
    }


    /**
      * Sets the value of the 'conductorId' field.
      * @param value The value of 'conductorId'.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.conductor.registro.UsuarioConductorCreado.Builder setConductorId(long value) {
      validate(fields()[0], value);
      this.conductorId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'conductorId' field has been set.
      * @return True if the 'conductorId' field has been set, false otherwise.
      */
    public boolean hasConductorId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'conductorId' field.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.conductor.registro.UsuarioConductorCreado.Builder clearConductorId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'keycloakUserId' field.
      * @return The value.
      */
    public java.lang.CharSequence getKeycloakUserId() {
      return keycloakUserId;
    }


    /**
      * Sets the value of the 'keycloakUserId' field.
      * @param value The value of 'keycloakUserId'.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.conductor.registro.UsuarioConductorCreado.Builder setKeycloakUserId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.keycloakUserId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'keycloakUserId' field has been set.
      * @return True if the 'keycloakUserId' field has been set, false otherwise.
      */
    public boolean hasKeycloakUserId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'keycloakUserId' field.
      * @return This builder.
      */
    public com.servicioTransporte.flota.eventos.conductor.registro.UsuarioConductorCreado.Builder clearKeycloakUserId() {
      keycloakUserId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UsuarioConductorCreado build() {
      try {
        UsuarioConductorCreado record = new UsuarioConductorCreado();
        record.conductorId = fieldSetFlags()[0] ? this.conductorId : (java.lang.Long) defaultValue(fields()[0]);
        record.keycloakUserId = fieldSetFlags()[1] ? this.keycloakUserId : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UsuarioConductorCreado>
    WRITER$ = (org.apache.avro.io.DatumWriter<UsuarioConductorCreado>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UsuarioConductorCreado>
    READER$ = (org.apache.avro.io.DatumReader<UsuarioConductorCreado>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.conductorId);

    out.writeString(this.keycloakUserId);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.conductorId = in.readLong();

      this.keycloakUserId = in.readString(this.keycloakUserId instanceof Utf8 ? (Utf8)this.keycloakUserId : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.conductorId = in.readLong();
          break;

        case 1:
          this.keycloakUserId = in.readString(this.keycloakUserId instanceof Utf8 ? (Utf8)this.keycloakUserId : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










