ALTER TABLE vehiculo ADD COLUMN IF NOT EXISTS fecha_creacion timestamp(6) without time zone;
ALTER TABLE conductor ADD COLUMN IF NOT EXISTS fecha_creacion timestamp(6) without time zone;
ALTER TABLE ruta ADD COLUMN IF NOT EXISTS fecha_creacion timestamp(6) without time zone;

CREATE TABLE IF NOT EXISTS audit_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp timestamp(6) without time zone NOT NULL,
    accion varchar(50) NOT NULL,
    categoria varchar(50) NOT NULL,
    detalles text,
    usuario varchar(255)
);
