server:
    port: 8083

spring:
    application:
        name: Seguimiento-Entrada-Telemetria
    Kafka:
      bootstrap-servers: localhost:9094
      properties:
          schema.registry.url: http://localhost:8086
          retries: 3
          retry.backoff.ms: 1000
      admin:
        fail-fast: false
      consumer:
        properties:
          auto.register.schemas: true

mqtt:
    broker-url: tcp://localhost:1883
    client-id: ingestion-service-client
    topic: vehicles/+/telemetry
    username: admin
    password: ${EMQX_DASHBOARD_PASSWORD}